# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
# image: python:latest

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pip
    - .tox

before_script:
  - export PATH="~/miniconda3/bin:$PATH"
  - python -V               # Print out python version for debugging
  - pip install --cache-dir=.pip -U pip setuptools

test:
  script:
  - pip install --cache-dir=.pip tox
  - tox -re py36,flake8,coverage,installation
  coverage: '/TOTAL.*\s+(\d+%)$/'

# run:
#   script:
#   - python setup.py bdist_wheel
#   # an alternative approach is to install and run:
#   - pip install dist/*
#   # run the command here
#   artifacts:
#     paths:
#     - dist/*.whl

# pages:
#   script:
#   - pip install sphinx sphinx-rtd-theme
#   - cd doc ; make html
#   - mv build/html/ ../public/
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
